config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    
    path('account/',include('account.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'main.views.handle_not_found'

main/urls.py
from django.urls import path
from .views import main_index,category,course,payment,create_card,courses_page
app_name = 'main'

urlpatterns = [
    path('',main_index,name='index'),
    path('category/',category,name='category'),
    path('course/<int:pk>/',course,name='course'),
    path('payment/<int:pk>/',payment,name='payment'),
    path('card/<int:pk>/',create_card,name='card'),
    path('courses/<int:pk>/',courses_page,name='courses')
    
]

templates/payment/card.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}


	
	
	<div class="page-content bg-white">
		<!-- inner page banner -->
		<div class="page-banner ovbl-dark" style="background-image:url(assets/images/banner/banner2.jpg);">
			<div class="container">
				<div class="page-banner-entry">
					<br><br><br><br><br><h1 class="text-white">Create your card for watch courses and learn!</h1>
				 </div>
			</div>
		</div>
		<!-- Breadcrumb row -->
		<div class="breadcrumb-row">
			<div class="container">
				<ul class="list-inline">
					<li><a href="#">Home</a></li>
					<li>Create_Card</li>
				</ul>
			</div>
		</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-6">
				<img src="{% static 'images/background/bg1.jpg' %}" alt="">
			</div>
			<div class="col-lg-6" style="margin-top:20px">
		<form class="contact-bx" method="post">
		{% csrf_token %}
		{{ form|crispy }}
	
		
		
		<div class="d-grid gap-2">
			<button class="btn btn-outline-success btn-lg btn-block" type="submit">Create the card</button>
			
		</div>
	</div>
	</div>	

	</form>
	</div>	


{% endblock %}

templates/payment/payment.html
{% extends 'layouts/base.html' %}
{% load static %}
{% load crispy_forms_filters %}
{% block content %}


	
	<div class="page-content bg-white">
		<!-- inner page banner -->
		<div class="page-banner ovbl-dark" style="background-image:url('static/images/banner/banner2.jpg');">
			<div class="container">
				<div class="page-banner-entry">
					<br><br><br><br><br><h1 class="text-white">Payment</h1>
				 </div>
			</div>
		</div>
		<!-- Breadcrumb row -->
		<div class="breadcrumb-row">
			<div class="container">
				<ul class="list-inline">
					<li><a href="#">Home</a></li>
					<li>Payment</li>
				</ul>
			</div>
		</div>
	<div class="container">
		<div class="row">
			
					<div class="col-lg-6">							
						<img src="{% static 'images/background/bg1.jpg' %}" alt="">
					</div>
					<div class="col-lg-6" style="margin-top:30px">
						<div class="heading-bx left">
							<h2 class="title-head">Welcome <span>{{ user.username }}</span></h2>
						</div>
						{% for row in card %}
							<p>To do payment pls add your card <a href="{% url 'main:card' row.id %}" style="color:blue">Card Add</a></p>
						{% endfor %}
						<form class="contact-bx" method="post">
						{% csrf_token %}
						{{ form|crispy }}
						
						{% for row in card %}
						
						
						Course price: ${{ row.price }}
						<br>
						<br>
						
						<div class="d-grid gap-2">
							<button class="btn btn-outline-success btn-lg btn-block" type="submit">Go to Courses</button>
							
						</div>
						{% endfor %}
						</form>
					</div>
				
		</div>
	</div>

{% endblock %}